version: '3.3'
services:
        db:
                build:
                        context: ./db
                restart: always
                environment:
                        POSTGRES_PASSWORD: mypass
        adminer:
                image: adminer
                restart: always
                ports:
                        - 8080:8080
                environment:
                        ADMINER_DEFAULT_DB_HOST: db
                        ADMINER_DEFAULT_DB_NAME: vhnews
                        ADMINER_DEFAULT_DB_DRIVER: pgsql
                depends_on:
                        - db
        webapp:
                build:
                        context: ./webapp
                ports:
                        - 8000:8000
                volumes:
                        - ./webapp/app:/app
                depends_on:
                        - db

